<?php
/**
 * Report sidebar — Mobile App tab
 *
 * @package Ninjalytics
 */

namespace NinjalyticsFree;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$mobile_app_video_url = 'https://www.youtube.com/shorts/cJJQQ9_ya18';
$mobile_app_embed_key = 'ninjalytics_mobile_app_oembed_v1';
$mobile_app_embed     = get_transient( $mobile_app_embed_key );

if ( false === $mobile_app_embed ) {
	$fetched_embed = wp_oembed_get( $mobile_app_video_url, array( 'width' => 280 ) );
	$mobile_app_embed = ( is_string( $fetched_embed ) && preg_match( '#youtube\.com|youtu\.be#i', $fetched_embed ) ) ? $fetched_embed : '';
	set_transient( $mobile_app_embed_key, $mobile_app_embed, $mobile_app_embed ? WEEK_IN_SECONDS : DAY_IN_SECONDS );
}
?>

<div class="ninjalytics-mobile-app">
	<header class="ninjalytics-sidebar-header">
		<div class="ninjalytics-sidebar-header-text">
			<h2 class="ninjalytics-sidebar-title"><?php esc_html_e( 'Mobile App', 'product-sales-report-for-woocommerce' ); ?></h2>
			<p class="ninjalytics-sidebar-subtitle"><?php esc_html_e( 'View reports on the go with Ninjalytics App.', 'product-sales-report-for-woocommerce' ); ?></p>
		</div>
	</header>

	<div class="ninjalytics-sidebar-body ninjalytics-mobile-app-body">
		<p><?php
			printf(
				/* translators: 1: Android link, 2: iOS link, 3: Ninjalytics Pro link */
				esc_html__( 'Access your reports on the go with the Ninjalytics app for %1$s or %2$s (beta) with %3$s', 'product-sales-report-for-woocommerce' ),
				'<a class="berrypress-link" href="https://play.google.com/store/apps/details?id=com.berrypress.ninjalytics" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Android', 'product-sales-report-for-woocommerce' ) . '</a>',
				'<a class="berrypress-link" href="https://apps.apple.com/app/ninjalytics/id6757487864" target="_blank" rel="noopener noreferrer">' . esc_html__( 'iOS', 'product-sales-report-for-woocommerce' ) . '</a>',
				'<a class="berrypress-link" href="' . esc_url( $this->getProductUrl() ) . '" target="_blank" rel="noopener noreferrer">' . esc_html__( 'Ninjalytics Pro', 'product-sales-report-for-woocommerce' ) . '</a>'
			);
			?></p>

		<?php if ( $mobile_app_embed ) { ?>
			<div class="ninjalytics-mobile-app-video">
				<p class="ninjalytics-mobile-app-video-label"><?php esc_html_e( 'See the app in action', 'product-sales-report-for-woocommerce' ); ?></p>
				<div class="ninjalytics-mobile-app-video-embed">
					<?php
					// oEmbed HTML is generated by WordPress; URL is fixed above.
					echo $mobile_app_embed; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
					?>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
